apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: antiginx
spec:
  type: ClusterIP
  selector:
    app: engine
  ports:
    - name: engine-port
      port: 5000
      targetPort: 5000
