apiVersion: v1
kind: Secret
metadata:
  name: antiginx-secrets
  namespace: antiginx
type: Opaque
stringData:
  DATABASE_URL: "<DATABASE_URL>"
  RABBITMQ_URL: "<RABBITMQ_URL>"
  JWT_SECRET: "<JWT_SECRET>"
  BACK_URL: "<BACK_URL>"
  ENGINE_ANTIGINX_CALL: "<ENGINE_ANTIGINX_CALL>"
  NEXT_PUBLIC_BACKEND_URL: "<NEXT_PUBLIC_BACKEND_URL>"