apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets
  - ../../apps/antiginx
  - ../../apps/data
  - ../../apps/monitoring
  - ../../addons/scan-targets
  - ../../addons/pgadmin
  - ../../addons/rabbitmq-management

images:
  - name: ghcr.io/prawo-i-piesc/engine-antiginx
    newTag: latest
  - name: ghcr.io/prawo-i-piesc/backend-antiginx
    newTag: latest
  - name: ghcr.io/prawo-i-piesc/frontend-antiginx
    newTag: latest
