name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
target-branch: main

categories:    
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'documentation'
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  patch:
    labels:
      - 'release-patch'
  minor:
    labels:
      - 'release-minor'
  major:
    labels:
      - 'release-major'
  default: minor

template: |
  ## What’s Changed

  $CHANGES
