services:
  engine-antiginx:
    image: ghcr.io/prawo-i-piesc/engine-antiginx:latest
    container_name: engine-antiginx
    restart: unless-stopped

    ports:
      - "${ENGINE_PORT}:5000"

    environment:
      - BACK_URL=${BACK_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - ENGINE_ANTIGINX_CALL=${ENGINE_ANTIGINX_CALL}

    networks:
      - antiginx-net

networks:
  antiginx-net:
    external: true