apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/antiginx
  - ../../apps/data
  - ../../apps/monitoring

images:
  - name: ghcr.io/prawo-i-piesc/backend-antiginx
    newTag: v0.6.13
  - name: ghcr.io/prawo-i-piesc/engine-antiginx
    newTag: v0.6.11
  - name: ghcr.io/prawo-i-piesc/frontend-antiginx
    newTag: v0.6.10
