apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: antiginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/prawo-i-piesc/frontend-antiginx:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: NEXT_PUBLIC_BACKEND_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"