apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets
  - ../../apps/antiginx
  - ../../apps/data
  - ../../apps/monitoring

images:
  - name: ghcr.io/prawo-i-piesc/engine-antiginx
    newTag: 0.6.16
  - name: ghcr.io/prawo-i-piesc/backend-antiginx
    newTag: 0.6.10
  - name: ghcr.io/prawo-i-piesc/frontend-antiginx
    newTag: 0.6.14
