apiVersion: v1
kind: Secret
metadata:
  name: antiginx-secrets
  namespace: antiginx
type: Opaque
stringData:
  # Engine
  # ANTIGINX_RDAP_URL: "<ANTIGINX_RDAP_URL>" - optional
  BACK_URL: "<BACK_URL>"
  RABBITMQ_URL: "<RABBITMQ_URL>"
  ENGINE_ANTIGINX_CALL: "<ENGINE_ANTIGINX_CALL>"
  # Backend
  # MAIL_TRANSPORT: "<MAIL_TRANSPORT>" - optional
  DATABASE_URL: "<DATABASE_URL>"
  JWT_SECRET: "<JWT_SECRET>"
  TOTP_ENCRYPTION_KEY: "<TOTP_ENCRYPTION_KEY>"
  PUBLIC_BASE_URL: "<PUBLIC_BASE_URL>"
  COOKIE_SECURE: "<COOKIE_SECURE>"
  GOOGLE_CLIENT_ID: "<GOOGLE_CLIENT_ID>"
  GOOGLE_CLIENT_SECRET: "<GOOGLE_CLIENT_SECRET>"
  GITHUB_CLIENT_ID: "<GITHUB_CLIENT_ID>"
  GITHUB_CLIENT_SECRET: "<GITHUB_CLIENT_SECRET>"
  MAIL_FROM: "<MAIL_FROM>"
  RESEND_API_KEY: "<RESEND_API_KEY>"
  # Frontend
  BACKEND_URL: "<BACKEND_URL>"
  TRUST_PROXY_HEADERS: "<TRUST_PROXY_HEADERS>"