apiVersion: v1
kind: Secret
metadata:
  name: antiginx-secrets
  namespace: antiginx
type: Opaque
stringData:
  DATABASE_URL: "<DATABASE_URL>"
  RABBITMQ_URL: "<RABBITMQ_URL>"
  JWT_SECRET: "<JWT_SECRET>"
  TOTP_ENCRYPTION_KEY: "<TOTP_ENCRYPTION_KEY>"
  PUBLIC_BASE_URL: "https://dev.antiginx.karwowski.dev"
  COOKIE_SECURE: "true"
  GOOGLE_CLIENT_ID: "<GOOGLE_CLIENT_ID>"
  GOOGLE_CLIENT_SECRET: "<GOOGLE_CLIENT_SECRET>"
  GITHUB_CLIENT_ID: "<GITHUB_CLIENT_ID>"
  GITHUB_CLIENT_SECRET: "<GITHUB_CLIENT_SECRET>"
  MAIL_TRANSPORT: "<MAIL_TRANSPORT>"
  MAIL_FROM: "<MAIL_FROM>"
  RESEND_API_KEY: "<RESEND_API_KEY>"
  BACKEND_URL: "http://backend-service.antiginx.svc.cluster.local:4000"
  BACK_URL: "<BACK_URL>"
  ENGINE_ANTIGINX_CALL: "<ENGINE_ANTIGINX_CALL>"
  NEXT_PUBLIC_BACKEND_URL: "<NEXT_PUBLIC_BACKEND_URL>"
  TRUST_PROXY_HEADERS: "true"
  ANTIGINX_RDAP_URL: "<ANTIGINX_RDAP_URL>"
