apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    env:
      - name: DUCKDNS_TOKEN
        valueFrom:
          secretKeyRef:
            name: traefik-secrets
            key: DUCKDNS_TOKEN
      - name: ACME_EMAIL
        valueFrom:
          secretKeyRef:
            name: traefik-secrets
            key: ACME_EMAIL
      - name: BASE_DOMAIN
        valueFrom:
          secretKeyRef:
            name: traefik-secrets
            key: BASE_DOMAIN
    persistence:
      enabled: true
      path: /data
      size: 128Mi
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.email=$(ACME_EMAIL)
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=*.$(BASE_DOMAIN)
      - --entrypoints.web.http.redirections.entrypoint.to=:443
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
