apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: data
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "<PGADMIN_DEFAULT_EMAIL>"
  PGADMIN_DEFAULT_PASSWORD: "<PGADMIN_DEFAULT_PASSWORD>"
