apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  namespace: scan-targets
spec:
  type: ClusterIP
  selector:
    app: webgoat
  ports:
    - name: webgoat-web-port
      port: 8080
      targetPort: 8080
    - name: webgoat-webwolf-port
      port: 9090
      targetPort: 9090
