apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: scan-targets
spec:
  type: ClusterIP
  selector:
    app: juice-shop
  ports:
    - name: juice-shop-port
      port: 3000
      targetPort: 3000
