apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
  namespace: scan-targets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
        - name: dvwa
          image: kaakaww/dvwa-docker:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
