services:
  frontend-antiginx:
    image: ghcr.io/prawo-i-piesc/frontend-antiginx:latest
    container_name: frontend-antiginx
    restart: unless-stopped

    ports:
      - "${FRONTEND_PORT}:3000"

    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

    networks:
      - antiginx-net

networks:
  antiginx-net:
    external: true