apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scan-targets
resources:
  - namespace.yaml
  - juice-shop/deployment.yaml
  - juice-shop/service.yaml
  - webgoat/deployment.yaml
  - webgoat/service.yaml
  - dvwa/deployment.yaml
  - dvwa/service.yaml
