services:
  backend-antiginx:
    image: ghcr.io/prawo-i-piesc/backend-antiginx:latest
    container_name: backend-antiginx
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT}:4000"

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}

    networks:
      - antiginx-net

networks:
  antiginx-net:
    external: true