apiVersion: v1
kind: Secret
metadata:
  name: traefik-acme-secrets
  namespace: kube-system
type: Opaque
stringData:
  ACME_EMAIL: "<ACME_EMAIL>"
  OVH_ENDPOINT: "ovh-eu"
  OVH_APPLICATION_KEY: "<OVH_APPLICATION_KEY>"
  OVH_APPLICATION_SECRET: "<OVH_APPLICATION_SECRET>"
  OVH_CONSUMER_KEY: "<OVH_CONSUMER_KEY>"
