apiVersion: v1
kind: Secret
metadata:
  name: traefik-secrets
  namespace: kube-system
type: Opaque
stringData:
  ACME_EMAIL: "<ACME_EMAIL>"
  DUCKDNS_TOKEN: "<DUCKDNS_TOKEN>"
  BASE_DOMAIN: "<BASE_DOMAIN>"
