apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: antiginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/prawo-i-piesc/backend-antiginx:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: JWT_SECRET
            - name: TOTP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: TOTP_ENCRYPTION_KEY
            - name: PUBLIC_BASE_UR
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: PUBLIC_BASE_UR
            - name: COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: COOKIE_SECURE
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: MAIL_TRANSPORT
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: MAIL_TRANSPORT
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: MAIL_FROM
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: antiginx-secrets
                  key: RESEND_API_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
