apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: antiginx
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: backend-port
      port: 4000
      targetPort: 4000
