apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-deployment
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop:v19.2.1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"