apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - antiginx/antiginx-secrets.yaml
  - data/data-secrets.yaml
  - monitoring/monitoring-secrets.yaml
  - pgadmin/pgadmin-secrets.yaml
